import Foundation

enum LegalDocuments {
    static let disclaimer = """
    IMPORTANT DISCLAIMER

    This application is intended for wellness and educational purposes only. It is NOT a medical device and should NOT be used to diagnose, treat, cure, or prevent any disease or health condition.

    The ECG screening results provided by this app are generated by an AI model and may not be accurate. Always consult a qualified healthcare professional for medical advice, diagnosis, or treatment.

    Do not disregard professional medical advice or delay seeking it because of information obtained from this app. In case of a medical emergency, call emergency services immediately.

    minuscule health Ltd makes no representations or warranties regarding the accuracy, reliability, or completeness of any health-related information provided by this app.

    By using this app, you acknowledge and agree to these terms.

    © 2026 minuscule health Ltd. All rights reserved.
    London, United Kingdom
    """

    static let disclaimerCN = """
    重要免责声明

    本应用程序仅供健康和教育目的使用。它不是医疗设备，不应用于诊断、治疗、治愈或预防任何疾病或健康状况。

    本应用提供的心电图筛查结果由AI模型生成，可能不准确。请始终咨询合格的医疗保健专业人员以获取医疗建议、诊断或治疗。

    请勿因从本应用获得的信息而忽视专业医疗建议或延迟就医。如遇医疗紧急情况，请立即拨打急救电话。

    minuscule health Ltd对本应用提供的任何健康相关信息的准确性、可靠性或完整性不作任何陈述或保证。

    使用本应用即表示您确认并同意这些条款。

    © 2026 minuscule health Ltd. 保留所有权利。
    英国伦敦
    """

    static let privacyPolicy = """
    PRIVACY POLICY

    Last updated: January 2026

    1. DATA COLLECTION
    det-evth collects ECG data from your Apple Watch via HealthKit and from imported PDF/image files. We also collect basic profile information you provide.

    2. DATA STORAGE
    All data is stored locally on your device. We do not transmit your health data to external servers.

    3. DATA SHARING
    Your data is only shared when you explicitly choose to share reports via email or other means.

    4. DATA RETENTION
    You can delete your data at any time through the app settings.

    5. YOUR RIGHTS
    Under GDPR, you have the right to access, rectify, and delete your personal data.

    6. CONTACT
    For privacy inquiries: privacy@minusculehealth.com

    © 2026 minuscule health Ltd
    """

    static let termsOfService = """
    TERMS OF SERVICE

    Last updated: January 2026

    1. ACCEPTANCE OF TERMS
    By using det-evth, you agree to these Terms of Service.

    2. SERVICE DESCRIPTION
    det-evth is a wellness application that provides ECG screening using AI technology. It is not a medical device.

    3. USER RESPONSIBILITIES
    - You must be at least 18 years old
    - You are responsible for the accuracy of information you provide
    - You should not rely solely on this app for medical decisions

    4. LIMITATIONS
    - The app is provided "as is" without warranties
    - We are not liable for any health decisions made based on app results
    - Results should be reviewed by a qualified healthcare professional

    5. INTELLECTUAL PROPERTY
    All content and technology in this app is owned by minuscule health Ltd.

    6. TERMINATION
    We reserve the right to terminate access for violations of these terms.

    7. GOVERNING LAW
    These terms are governed by the laws of the United Kingdom.

    © 2026 minuscule health Ltd
    """
}
